weights: runs\train-seg\gelan-c-seg-aug\weights\last.pt
cfg: ''
data: E:\yolov9\data\credium.yaml
hyp:
  lr0: 0.0001
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  dfl: 1.5
  iou_t: 0.2
  anchor_t: 5.0
  anchors: 3
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.9
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.15
  copy_paste: 0.3
epochs: 20
batch_size: 2
imgsz: 1024
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: runs\train-seg
name: gelan-c-seg-aug
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
close_mosaic: 0
mask_ratio: 4
no_overlap: true
save_dir: runs\train-seg\gelan-c-seg-aug
